/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gnu_apl_Native */

#ifndef _Included_org_gnu_apl_Native
#define _Included_org_gnu_apl_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gnu_apl_Native
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_gnu_apl_Native_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
