/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gnu_apl_Native */

#ifndef _Included_org_gnu_apl_Native
#define _Included_org_gnu_apl_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gnu_apl_Native
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_gnu_apl_Native_init
  (JNIEnv *, jclass);

/*
 * Class:     org_gnu_apl_Native
 * Method:    evalExpression
 * Signature: (Ljava/lang/String;)Lorg/gnu/apl/AplValue;
 */
JNIEXPORT jobject JNICALL Java_org_gnu_apl_Native_evalExpression
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_gnu_apl_Native
 * Method:    evalWithIo
 * Signature: (Ljava/lang/String;Ljava/io/StringWriter;Ljava/io/StringWriter;Ljava/io/StringWriter;)V
 */
JNIEXPORT void JNICALL Java_org_gnu_apl_Native_evalWithIo
  (JNIEnv *, jclass, jstring, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
